### ISSUE TITLE
Heroku support?

### ISSUE THREAD

**Issue by eliotfowler** [pjay/plush#2]
Have you had any luck getting this running on Heroku? I added the redis to go plugin and added `redis.url=${REDISTOGO_URL}` to the application.conf file but I'm getting a db connection error when trying to log in.

If it matters, I'm trying to use 

```
username: admin
password: admin
```

to log in.

**Comment by pjay** [comment]
Hi Eliot,

I haven't tried it on Heroku yet.

Currently the Redis integration is very basic, and you should modify `app/models/RedisClient.scala` with the correct host/port from `REDISTOGO_URL`. You should also send an `AUTH` command to the Redis server, probably by adding the following line to the body of `RedisConnection` (untested):

```
redis.auth("your_password_from_REDISTOGO_URL")
```

In the future the app will read the Redis configuration from its config file.
